version: '3.8'

services:
  bot:
    image: cashly-bot:latest
    container_name: cashly-bot
    build:
      context: build
      dockerfile: build/Dockerfile
    volumes:
      - ./family.json:/root/family.json:ro
      - ./config:/root/config:ro
    env_file:
      - .env
    environment:
      - CONFIG_PATH=config/config.yml
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
